import type { FeedGroup } from '~/types/feed'
import { getGhAvatar } from './utils/img'

export default <FeedGroup[]>[{
    name: '相谈甚多',
    desc: '',
    entries: [{
        author: 'LineXic',
        sitenick: '书屋',
        title: 'LineXic书屋',
        desc: '念念不忘，必有回响',
        link: 'https://linexic.top',
        feed: 'https://linexic.top/atom.xml',
        icon: 'https://linexic.top/logo.png',
        avatar: 'https://linexic.top/avatar.webp',
        archs: ['Hexo', 'Vercel'],
        date: '2025-01-24',
        comment: '技术分享，高中生活，赛博神医',
    },],
    },{
    name: '网上邻居',
    desc: '哔——啵——电波通讯中，欢迎常来串门。',
    entries: [{
        author: '枫落丰源',
        title: '枫落丰源\'s Blog',
        desc: '只要开始追赶，就已经走在胜利的路上',
        link: 'https://feng1026.top',
        feed: 'https://feng1026.top/feed',
        icon: 'https://s21.ax1x.com/2024/10/19/pAaAoIx.png',
        avatar: 'https://q1.qlogo.cn/g?b=qq&nk=435900598&src_uin=www.jlwz.cn&s=0',
        archs: ['Typecho', '虚拟主机'],
        date: '2025-01-24',
        comment: '生活随笔，内有暴食海獭!',
    },{
        author: 'MeowcoQAQ',
        title: 'MeowcoQAQ\'s Blog',
        desc: '还是音 MIDI 大佬',
        link: 'https://blog.mcneko.com',
        feed: 'https://blog.mcneko.com/feed',
        icon: '',
        avatar: 'https://sc.midishow.net/source/avatar/91/914504.jpg',
        archs: ['WordPress', '服务器'],
        date: '2025-01-24',
        comment: '分享内容与琐事，喵喵喵喵喵喵~',
    },{
        author: 'Steven',
        title: 'Steven\'s Blog',
        desc: '没有既定的终点，只有无限的探索',
        link: 'https://blog.stevenw.cc',
        feed: 'https://blog.stevenw.cc/sitemap.xml',
        icon: 'https://blog.stevenw.cc/upload/logo.png',
        avatar: 'https://blog.stevenw.cc/upload/logo.png',
        archs: ['Halo', '服务器'],
        date: '2025-02-07',
        comment: 'MC同好',
    },],
}]
